id = "rux"
name = "Rux"
version = "0.1.0"
schema_version = 1
authors = ["Ivan Muzyka"]
description = "Rux language support for Zed"
repository = "https://github.com/rux-lang/Zed"


[grammars.rux]
repository = "https://github.com/rux-lang/Zed"
rev = "bd5b5231c3448ac8900f44250d7f1e5bce31eaad"
